<?php

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class Dollypack_Edit_Custom_Ability extends Dollypack_Ability {

	protected $id          = 'edit-custom-ability';
	protected $name        = 'dollypack/edit-custom-ability';
	protected $label       = 'Edit Custom Ability';
	protected $description = 'Create, read, test, turn on, and turn off constrained custom abilities generated by Dollypack.';

	public function execute( $input ) {
		$action     = $input['action'] ?? '';
		$name       = $input['name'] ?? '';
		$payload    = $input['payload'] ?? array();
		$test_input = $input['test_input'] ?? array();

		switch ( $action ) {
			case 'read':
				return Dollypack_Custom_Ability_Manager::read_custom_ability( $name );

			case 'write':
				return Dollypack_Custom_Ability_Manager::write_custom_ability( $name, $payload );

			case 'test':
				return Dollypack_Custom_Ability_Manager::test_custom_ability( $name, $test_input );

			case 'turn_on':
				return Dollypack_Custom_Ability_Manager::turn_on_custom_ability( $name );

			case 'turn_off':
				return Dollypack_Custom_Ability_Manager::turn_off_custom_ability( $name );

			default:
				return new WP_Error(
					'invalid_custom_ability_action',
					'The action parameter must be one of: read, write, test, turn_on, turn_off.'
				);
		}
	}

	public function get_input_schema() {
		return array(
			'type'       => 'object',
			'properties' => array(
				'action'    => array(
					'type'        => 'string',
					'enum'        => array( 'read', 'write', 'test', 'turn_on', 'turn_off' ),
					'description' => 'Operation to perform on a custom ability.',
					'required'    => true,
				),
				'name'      => array(
					'type'        => 'string',
					'description' => 'Custom ability slug or display name. Optional for read when listing all generated abilities.',
				),
				'payload'   => array(
					'type'        => 'object',
					'description' => 'Ability payload for write. Provide label, description, execute_body, input_schema, output_schema, and optional annotations.',
				),
				'test_input' => array(
					'type'        => 'object',
					'description' => 'Optional input object to pass to execute() during test.',
				),
			),
		);
	}

	public function get_output_schema() {
		return array(
			'type'        => 'object',
			'description' => 'Details about the requested custom ability operation.',
		);
	}

	public function get_meta() {
		return array(
			'show_in_rest' => true,
			'annotations'  => array(
				'destructive' => true,
				'idempotent'  => false,
			),
		);
	}
}
